from item import Item
from math import floor


# Roe object that can age itself by a day, and sell itself
# if it has completely aged.
class Roe:
    def __init__(self, fish_object):
        self.fish_object = fish_object
        self.days_aged = 0

    def age_one_day(self):
        self.days_aged += 1
        if self.is_finished():
            if "STURGEON" != self.fish_object.name:
                return 2 * roe_price(self.fish_object)
            else:
                return Item.CAVIAR.value

    def is_finished(self):
        return (("STURGEON" != self.fish_object.name and self.days_aged > 2) or
                ("STURGEON" == self.fish_object.name and self.days_aged > 3))


# Return the price of roe generated by a Fish.
def roe_price(fish_object):
    return floor(30 + fish_object.value/2)
